### ISSUE TITLE
How to block update notification on Android

### ISSUE THREAD

**Issue by sleepdeal** [zoffline/zwift-offline#252]
![20230716_174928](https://github.com/zoffline/zwift-offline/assets/139680805/d25de52a-c2e8-4a88-a1cb-8d38ef0bb46b)
I'm using zwift on my tablet and vpn host doesn't work well so using fake-dns instead
There is no problem playing with fake-dns, but update notification appear after 2~3 weeks
Zwift update is turned off on the Play Store
When the notification pop up, it can't be play so new update and apply obb.apk will solve the problem. but it's really annoying

![20230716_175507](https://github.com/zoffline/zwift-offline/assets/139680805/7d39caa7-cd9a-4b50-90b3-2480fe9435df)
I checked us-or-rly101.zwift.com and secure.zwift.com are bypassed fine, but cdn.zwift.com is not bypassed
I can't use vpn host and need to use fake-dns, is there a solution?

**Comment by oldnapalm** [comment]
You can try adding `    dns.addname('cdn.zwift.com.', server_ip)` here https://github.com/zoffline/zwift-offline/blob/master/fake_dns.py#L60 but I'm not sure it will prevent the update requirement.

Maybe https://github.com/zoffline/zwift-offline/blob/master/cdn/gameassets/ZwiftAndroid_ver_cur.xml needs to be updated, I noticed it doesn't contain `update_by` and `mandatory_update_by` like the current official file.

It's also possible that the app looks for updates in Play Store, even though you have disabled automatic update.

**Comment by sleepdeal** [comment]
Hi...
You can ask me why build it instead of running standalone.py
I need standalone exe to run on my brother PC
but I tried zwift_offline.py with pyinstaller several times, it kept failing and i don't know why
Can you build and upload standalone exe include cdn.zwift.com in fake_dns?

**Comment by oldnapalm** [comment]
You can fork the repo, make the changes you want and modify .github/workflows/pyinstaller.yaml like this, then the exe will be found under actions / workflow name / artifacts (you can also delete ci.yml)

```
name: pyinstaller

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - uses: engineerd/configurator@v0.0.8
      with:
        name: "upx.exe"
        url: "https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip"
        pathInArchive: "upx-4.0.2-win64/upx.exe"

    - run: pip install -r requirements.txt
    - run: pip install pyinstaller git+https://github.com/oldnapalm/garmin-uploader.git
    - run: pyinstaller standalone.spec

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
```
